In [5]:
import pandas as pd
data = pd.read_csv("./spambase/spambase.data")

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   word_freq_make              4601 non-null   float64
 1   word_freq_address           4601 non-null   float64
 2   word_fre_all                4601 non-null   float64
 3   word_freq_3d                4601 non-null   float64
 4   word_freq_our               4601 non-null   float64
 5   word_freq_over              4601 non-null   float64
 6   word_freq_remove            4601 non-null   float64
 7   word_freq_internet          4601 non-null   float64
 8   word_freq_order             4601 non-null   float64
 9   word_freq_mail              4601 non-null   float64
 10  word_freq_receive           4601 non-null   float64
 11  word_freq_will              4601 non-null   float64
 12  word_freq_people            4601 non-null   float64
 13  word_freq_report            4601 

In [8]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [9]:
# Data load and pre-processing
data = pd.read_csv("./spambase/spambase.data")
data=data.drop_duplicates()
# x are the dependent variables and y is the target variable
X = data.drop('Class',axis=1)
y = data['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=1)

In [10]:
data.head()

word_freq_make  word_freq_address  word_fre_all  word_freq_3d  \
0            0.00               0.64          0.64           0.0   
1            0.21               0.28          0.50           0.0   
2            0.06               0.00          0.71           0.0   
3            0.00               0.00          0.00           0.0   
4            0.00               0.00          0.00           0.0   

   word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0           0.32            0.00              0.00                0.00   
1           0.14            0.28              0.21                0.07   
2           1.23            0.19              0.19                0.12   
3           0.63            0.00              0.31                0.63   
4           0.63            0.00              0.31                0.63   

   word_freq_order  word_freq_mail  ...  char_freq_;  char_freq_(  \
0             0.00            0.00  ...         0.00        0.000   
1             0.00            0.94  ...         0.00        0.132   
2             0.64            0.25  ...         0.01        0.143   
3             0.31            0.63  ...         0.00        0.137   
4             0.31            0.63  ...         0.00        0.135   

   char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
0          0.0        0.778        0.000        0.000   
1          0.0        0.372        0.180        0.048   
2          0.0        0.276        0.184        0.010   
3          0.0        0.137        0.000        0.000   
4          0.0        0.135        0.000        0.000   

   capital_run_length_average  capital_run_length_longest  \
0                       3.756                          61   
1                       5.114                         101   
2                       9.821                         485   
3                       3.537                          40   
4                       3.537                          40   

   capital_run_length_total  Class  
0                       278      1  
1                      1028      1  
2                      2259      1  
3                       191      1  
4                       191      1  

[5 rows x 58 columns]

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [13]:
# fit the LG model -- random_state is used to shuffle the data; max_iter is max # of iterations for solver to converge (default is 100)
model = LogisticRegression(random_state=1, max_iter=1000).fit(X_train, y_train)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [14]:
# print the report
print(f"Performance on TEST\n*******************\n{classification_report(y_test, model.predict(X_test))}")
print(f"Performance on TRAIN\n********************\n{classification_report(y_train, model.predict(X_train))}")

Performance on TEST
*******************
              precision    recall  f1-score   support

           0       0.93      0.95      0.94       759
           1       0.92      0.90      0.91       504

    accuracy                           0.93      1263
   macro avg       0.93      0.93      0.93      1263
weighted avg       0.93      0.93      0.93      1263

Performance on TRAIN
********************
              precision    recall  f1-score   support

           0       0.92      0.95      0.94      1772
           1       0.92      0.88      0.90      1175

    accuracy                           0.92      2947
   macro avg       0.92      0.92      0.92      2947
weighted avg       0.92      0.92      0.92      2947



In [15]:
model.coef_

array([[-9.76812195e-02,  7.66496790e-02,  9.68343758e-02,
         8.93165561e-01,  4.72161424e-01,  6.27370817e-01,
         2.20334227e+00,  8.93579697e-01,  5.31001105e-01,
         2.39911346e-02,  5.68838090e-01, -1.08902749e-01,
        -1.52514765e-01,  7.79374358e-02,  6.48127012e-01,
         7.75936585e-01,  8.73738047e-01,  6.11804235e-02,
         2.69030760e-02,  7.55959040e-01,  2.88909085e-01,
         2.59715110e-01,  2.41460051e+00,  3.14184379e-01,
        -1.57952351e+00, -1.11956609e+00, -3.18970017e+00,
         4.36973615e-01, -1.05291912e+00, -1.47061768e-01,
        -3.05112506e-01, -8.05150947e-02, -7.76728822e-01,
        -2.48712258e-01, -1.30095645e+00,  8.86501389e-01,
        -3.59679208e-01, -5.02011163e-01, -7.02554701e-01,
        -2.82857989e-01, -1.13595517e+00, -1.73915738e+00,
        -8.29188919e-01, -1.11568846e+00, -6.65527652e-01,
        -1.44369483e+00, -7.97551088e-01, -1.40698774e+00,
        -1.30321784e+00, -5.89612841e-01, -9.32025374e-0

In [16]:
model.intercept_

array([-1.18513106])

In [17]:
model.decision_function(X.iloc[0:30])

array([ 0.41197139,  3.35847571,  9.89648015,  1.33554459,  1.33612954,
        1.29787078,  1.435401  ,  1.32616032,  7.80293451,  1.61578621,
        1.86046652,  0.30915898,  0.40127043,  1.98260274,  5.99352106,
        2.4698502 ,  0.45742975,  3.18699002,  0.53212542,  4.98113039,
       -1.38179027,  2.26563928,  1.98760209,  0.97928051, -1.43229853,
        2.26521146,  3.78646326,  1.33051498,  7.30700759, -0.75489195])

In [18]:
np.sum( model.coef_*X.iloc[0:1].values) + model.intercept_

array([0.41197139])

In [19]:
model.predict(X.iloc[0:30])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0])

In [20]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [22]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)


In [23]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.93      1.00      0.96        13
           2       1.00      0.83      0.91         6

    accuracy                           0.97        30
   macro avg       0.98      0.94      0.96        30
weighted avg       0.97      0.97      0.97        30

