In [2]:
from transformers import pipeline

2024-04-18 19:46:51.799000: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-18 19:46:53.473999: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-18 19:46:56.611299: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [6]:
en_to_fr_translator = pipeline("translation_en_to_fr")

No model was supplied, defaulted to google-t5/t5-base and revision 686f1db (https://huggingface.co/google-t5/t5-base).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.11/site-packages/transformers/models/t5/tokenization_t5_fast.py:171: FutureWarning: This tokenizer was incorrectly instantiated with a model max length of 512 which will be corrected in Transformers v5.
For now, this behavior is kept to avoid breaking backwards compatibility when padding/encoding with `truncation is True`.
- Be aware that you SHOULD NOT rely on google-t5/t5-base automatically truncating your input to 512 when padding/encoding.
- If you want to encode/pad to sequences longer than 512 you can either instantiate this tokenizer with `model_max_length` or pass `max_length` when encoding/padding.
- To avoid this warning, please instantiate this tokenizer with `model_max_length` set to your preferred value.
  warnings.warn(


In [7]:
en_to_fr_translator("Hello, my name is Joe.")

[{'translation_text': 'Bonjour, mon nom est Joe.'}]

## As we can see, it has a list of dictionaries. This allows BATCHING!

In [2]:
en_to_fr_translator(["Machine learning is a branch of Artificial Intelligence",
                 "The United States Declaration of Independence was written in 1776."])

[{'translation_text': 'L’apprentissage automatique est une branche de l’intelligence artificielle'},
 {'translation_text': "La Déclaration d'indépendance des États-Unis a été rédigée en 1776."}]

In [3]:
summarizer = pipeline("summarization")
summarizer("""NLP is one of the oldest areas of AI and has a long history dating back at least to the 1950s.
    One of the first efforts to garner public attention was the Georgetown-IBM experiment in 1954, which
    attempted automatically translate Russian sentences to English.
    Here is a screenshot from an early, famous NPL program called ELIZA, developed at MIT between 1964 and
    1967. THe ELIZA program prompted users with questions in natural language text and enabled them to
    submit answers, also in natural language. The goal was to simulate a psychotherapy session.""")

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/1.80k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

Your max_length is set to 142, but your input_length is only 135. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=67)


[{'summary_text': ' NLP is one of the oldest areas of AI and has a long history dating back at least to the 1950s . One of the first efforts to garner public attention was the Georgetown-IBM experiment in 1954, which attempted automatically translate Russian sentences to English . The goal was to simulate a psychotherapy session .'}]

# Look for models at Huggingface HUB!

In [4]:
en_sp_translator = pipeline(model="Helsinki-NLP/opus-mt-en-es")
en_sp_translator("Hello, my name is Joe.")

config.json:   0%|          | 0.00/1.47k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/312M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/44.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/802k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/826k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.59M [00:00<?, ?B/s]

[{'translation_text': 'Hola, mi nombre es Joe.'}]

In [3]:
# create a pipeline with the default model for the task
image_to_text = pipeline('image-to-text')

# use the model on an image; in this case we can simply pass it the path to a file
image_to_text("data/monkie.JPG")

No model was supplied, defaulted to ydshieh/vit-gpt2-coco-en and revision 65636df (https://huggingface.co/ydshieh/vit-gpt2-coco-en).
Using a pipeline without specifying a model name and revision in production is not recommended.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration. Please open a PR/issue to update `preprocessor_config.json` to use `image_processor_type` instead of `feature_extractor_type`. This warning will be removed in v4.40.
/usr/local/lib/python3.11/site-packages/transformers/generation/utils.py:1178: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#i

[{'generated_text': 'a stuffed animal with a face on it '}]

# We can auto-tokenize using the tokenizer from what model we want to use!

*Basically, get me the tokenizer from the pretrained model*

In [8]:
from transformers import AutoTokenizer
checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [9]:
d = tokenizer("The food was good, not bad at all.")
print(d)

{'input_ids': [101, 1996, 2833, 2001, 2204, 1010, 2025, 2919, 2012, 2035, 1012, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [10]:
tokenizer.convert_ids_to_tokens(d['input_ids'])

['[CLS]',
 'the',
 'food',
 'was',
 'good',
 ',',
 'not',
 'bad',
 'at',
 'all',
 '.',
 '[SEP]']

In [11]:
d2 = tokenizer("The food was good, not bad at all.", "The food was bad, not good at all.")
print(d2)

{'input_ids': [101, 1996, 2833, 2001, 2204, 1010, 2025, 2919, 2012, 2035, 1012, 102, 1996, 2833, 2001, 2919, 1010, 2025, 2204, 2012, 2035, 1012, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [12]:
tokenizer.convert_ids_to_tokens(d2['input_ids'])

['[CLS]',
 'the',
 'food',
 'was',
 'good',
 ',',
 'not',
 'bad',
 'at',
 'all',
 '.',
 '[SEP]',
 'the',
 'food',
 'was',
 'bad',
 ',',
 'not',
 'good',
 'at',
 'all',
 '.',
 '[SEP]']

### Batching inputs

In [13]:
tokenizer(["The food was good, not bad at all.", "The food was bad, not good at all."])

{'input_ids': [[101, 1996, 2833, 2001, 2204, 1010, 2025, 2919, 2012, 2035, 1012, 102], [101, 1996, 2833, 2001, 2919, 1010, 2025, 2204, 2012, 2035, 1012, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

### **FOR THIS EXAMPLE, token_type_ids ARE BOTH LISTS OF 0, SINCE WITH BACTHING, THEY BOTH THINK THEY ARE THE FIRST SENTENCE!!**

Pytorch Tensor Conversion for the input_ids

In [14]:
# 'pt' converts it to pytorch format
d = tokenizer("The food was good, not bad at all", return_tensors="pt")
print(d)
tensors = d['input_ids']
print(type(tensors), tensors.shape)
print(tensors)

{'input_ids': tensor([[ 101, 1996, 2833, 2001, 2204, 1010, 2025, 2919, 2012, 2035,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
<class 'torch.Tensor'> torch.Size([1, 11])
tensor([[ 101, 1996, 2833, 2001, 2204, 1010, 2025, 2919, 2012, 2035,  102]])


In [15]:
tokenizer(["The food was good", "The food was bad, not good at all."], return_tensors='pt')

ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`input_ids` in this case) have excessive nesting (inputs type `list` where type `int` is expected).

### ^*This blows up because the set of tokens are different lengths. ANNs (this transformer) wants a rectangular shape*

To fix this, we pad the shorter one with '0' to make it match the longer one

In [16]:
# Here, we properly pad our input data
tokenizer(["The food was good", "The food was bad, not good at all."], return_tensors='pt', padding=True)

{'input_ids': tensor([[ 101, 1996, 2833, 2001, 2204,  102,    0,    0,    0,    0,    0,    0],
        [ 101, 1996, 2833, 2001, 2919, 1010, 2025, 2204, 2012, 2035, 1012,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

### OMG!!! As we can see, it padded properly! However, we don't want to send in a bunch of '0' garbage data to the model, so that is where ***attention_mask*** comes into play! It tells the model what it should not pay attention to, i.e. the padded zeros.

In [30]:
d3 = tokenizer(["The food was good", "The food was bad, not good at all."], padding=True)
tokenizer.convert_ids_to_tokens(d3['input_ids'][0])

['[CLS]',
 'the',
 'food',
 'was',
 'good',
 '[SEP]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]']

## **Models from Checkpoints and Language Embeddings**

Use the 'automodel' class to use a pretrained checkpoint model

In [31]:
from transformers import AutoModel
model = AutoModel.from_pretrained(checkpoint)

model(tensors)

BaseModelOutput(last_hidden_state=tensor([[[ 0.6970, -0.1998,  0.2270,  ...,  0.6403,  1.3413, -0.5515],
         [ 0.8073, -0.5202, -0.2255,  ...,  0.6772,  1.4120, -0.2586],
         [ 0.6202, -0.2049,  0.0489,  ...,  0.7242,  1.1984, -0.3907],
         ...,
         [ 0.3216, -0.2606,  0.5487,  ...,  0.5800,  0.8610, -0.5438],
         [ 0.0175, -0.3026,  0.4759,  ...,  0.2545,  1.2632, -0.7216],
         [ 1.1879,  0.0695,  0.8660,  ...,  0.7701,  1.0356, -1.0489]]],
       grad_fn=<NativeLayerNormBackward0>), hidden_states=None, attentions=None)

In [32]:
print(model.embeddings.word_embeddings(tensors))

tensor([[[ 0.0399, -0.0102, -0.0204,  ...,  0.0616,  0.0220,  0.0227],
         [-0.0478, -0.0107,  0.0038,  ..., -0.0348, -0.0126, -0.0481],
         [-0.0286, -0.0016, -0.0013,  ..., -0.0032,  0.0111, -0.0510],
         ...,
         [-0.0435, -0.0050, -0.0070,  ..., -0.0320, -0.0576,  0.0114],
         [-0.0679, -0.0115, -0.0107,  ...,  0.0502,  0.0023, -0.0396],
         [-0.0211, -0.0065, -0.0107,  ..., -0.0234,  0.0061, -0.0065]]],
       grad_fn=<EmbeddingBackward0>)


In [33]:
inputs = tokenizer("The food was good, not bad at all.", return_tensors="pt")['input_ids']
output = model(inputs)
output.last_hidden_state.shape

torch.Size([1, 12, 768])

In [34]:
from transformers import AutoModelForSequenceClassification
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

In [35]:
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model2 = AutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[-3.9782,  4.3248]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [36]:
outputs.logits.shape

torch.Size([1, 2])

In [37]:
outputs.logits

tensor([[-3.9782,  4.3248]], grad_fn=<AddmmBackward0>)

In [38]:
import torch
predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
print(predictions)

tensor([[2.4772e-04, 9.9975e-01]], grad_fn=<SoftmaxBackward0>)


In [39]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [43]:
def get_prediction(logits):
    results = []
    predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
    for p in range(len(predictions)):
        if predictions[p][0] > predictions[p][1]:
            results.append(model.config.id2label[0])
        else:
            results.append(model.config.id2label[1])
    return results

In [44]:
# a list of inputs to try our model on
inputs = ["I am happy", "I am sad", "This is good", "This is bad", "I enjoyed the pizza", "I am worried about the exam"]

# tokenize the inputs; we'll need to use padding here, and we'll just grab the input_ids object
tokens = tokenizer(inputs, return_tensors="pt", padding=True)['input_ids']

# pass the tokens through the model
outputs = model(tokens)

# get predictions from our model outputs using the post-processing function
predictions = get_prediction(outputs.logits)

# print the prediction
for i in range(len(inputs)):
    print(f"Sentence: {inputs[i]}; prediction: {predictions[i]};")

Sentence: I am happy; prediction: POSITIVE;
Sentence: I am sad; prediction: NEGATIVE;
Sentence: This is good; prediction: POSITIVE;
Sentence: This is bad; prediction: NEGATIVE;
Sentence: I enjoyed the pizza; prediction: POSITIVE;
Sentence: I am worried about the exam; prediction: NEGATIVE;
